### ISSUE TITLE
Cache priming question

### ISSUE THREAD

**Issue by shapiromatron** [OpenDataPolicingNC/Traffic-Stops#42]
Does the cache need to be primed using `?format=json` at the end of the URI? Otherwise are we just priming the html view instead of the json view?

**Comment by copelco** [comment]
Good question. I think django-rest-framework is probably being smart about it, because big datasets load quickly upon initial load after priming the cache:

```
traffic_stops@ip-172-31-25-2:/var/www/traffic_stops$ time /var/www/traffic_stops/manage.sh prime_cache http://0.0.0.0:8000/api/agency/                                                                              
real    5m56.516s
user    0m2.536s
sys     0m0.162s

traffic_stops@ip-172-31-25-2:/var/www/traffic_stops$ time /var/www/traffic_stops/manage.sh prime_cache http://0.0.0.0:8000/api/agency/
real    0m4.697s
user    0m2.397s
sys     0m0.080s
```

Then immediately visiting [Charlotte](https://opendatapolicingnc.com/agency/50/) in a browser, it loads really quick. Though maybe we should also cache the ``use_of_force``, ``searches``, and ``contraband_hit_rate`` endpoints to make it even faster.
